### ISSUE TITLE
Создание фрагмента

### ISSUE THREAD

**Issue by Kortvk** [Doldrums/Final_Project#14]
https://github.com/Doldrums/Final_Project/blob/017990eef558ed1378c20705997b3e4cad96d743/app/src/main/java/com/example/final_project/Fragments/BeginFragment.kt#L38
В этом нет смысла и какой-то выгоды.  Ты так и так создаешь новый инстанс фрагмента, но делаешь это через companion object. Не вижу профита здесь. Так же apply тут бесполезен, так как он вернет все тот же Фрагмент

**Comment by Doldrums** [comment]
сейчас туда добавлены еще всякие аргументы ==> теперь это использование можно считать оправданным? или нужно что-то поправить?

**Comment by Kortvk** [comment]
Теперь лучше, но желательно явно называть аргументы чтобы было понятно для чего используется параметр

**Comment by Doldrums** [comment]
ясно, исправлено
