### ISSUE TITLE
Функция, которая ни на что не влияет

### ISSUE THREAD

**Issue by Kortvk** [Doldrums/Final_Project#16]
https://github.com/Doldrums/Final_Project/blob/017990eef558ed1378c20705997b3e4cad96d743/app/src/main/java/com/example/final_project/MainActivity.kt#L24
Здесь делается запрос, но ответ никак не обрабатывается

**Comment by 4nt0n64r** [comment]
Да, я просто тренировался получать данные, нужно в onResponse запускать функцию из адаптера, чтобы добавить туда пришедшие данные. С этим пока сложно.

**Comment by Kortvk** [comment]
Почитай про лямда-выражения. Здесь они тебе помогут
