### ISSUE TITLE
Область видимости свойства

### ISSUE THREAD

**Issue by Kortvk** [Doldrums/Final_Project#17]
https://github.com/Doldrums/Final_Project/blob/017990eef558ed1378c20705997b3e4cad96d743/app/src/main/java/com/example/final_project/RecyclerItemClickListener.kt#L16
Здесь надо `private`, так как больше нигде это свойство не используется. 
https://kotlinlang.ru/docs/reference/visibility-modifiers.html

**Comment by Doldrums** [comment]
исправлено
